name: Build Python

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "50 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: List
        run: ls -ll

      - name: Instalar requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        id: tests
        continue-on-error: true
        run: pytest -v > resultado_teste

      - name: Verificar resultado do Pytest
        run: |
          if [ "${{ steps.tests.outcome }}" == "failure" ]; then
            echo "O step 'test' falhou"
          else
            echo "O step rodou!"
          fi

      - name: Forçar falha se Pytest falhar
        if: ${{ steps.tests.outcome}} == "failure"
        run: exit 1

      - name: Upload file
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: resultado
          path: resultado_teste
