name: Build Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: List
        run: ls -ll

      - name: Instalar requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: pytest -v > resultado_teste

      - name: Sucesso
        if: ${{ success() }}
        run: echo "Todos os steps foram concluídos com sucesso"

      - name: Erro
        if: ${{ failure() }}
        run: echo "Falhou"

      - name: Upload file
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: resultado
          path: resultado_teste
