name: CI com badge estático (SVG)

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com cobertura
        run: pytest -v --cov=sisrel --cov-report=xml:coverage.xml

      - name: Gerar Badge estatico de cobertura
        id: badge
        run: |
          # Extrai o valor da cobertura (0.x) do coverage.xml
           COVERAGE=$(grep -oPm1 '(?<=line-rate=")[^"]+' coverage.xml)
           PERCENT=$(python -c "print(int(float('${COVERAGE}')*100))")

           echo "Cobertura: ${PERCENT}%"
           echo "cobertura=${PERCENT}" >> $GITHUB_OUTPUT

           # Define cor conforme o nível (HEX válido)
           if   [ "${PERCENT}" -ge 90 ]; then COLOR="#4c1";      # brightgreen
           elif [ "${PERCENT}" -ge 75 ]; then COLOR="#97ca00";   # green
           elif [ "${PERCENT}" -ge 50 ]; then COLOR="#dfb317";   # yellow
           else                               COLOR="#e05d44";   # red
           fi

           echo "Cor usada no badge: ${COLOR}"
           cat > coverage-badge.svg <<SVG
           <svg xmlns="http://www.w3.org/2000/svg" width="110" height="20" role="img" aria-label="coverage: ${PERCENT}%">
           <linearGradient id="a" x2="0" y2="100%">
             <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
             <stop offset="1" stop-opacity=".1"/>
           </linearGradient>
           <rect rx="3" width="110" height="20" fill="#555"/>
           <rect rx="3" x="60" width="50" height="20" fill="${COLOR}"/>
           <path fill="${COLOR}" d="M60 0h4v20h-4z"/>
           <rect rx="3" width="110" height="20" fill="url(#a)"/>
           <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
             <text x="30" y="15" fill="#010101" fill-opacity=".3">coverage</text>
             <text x="30" y="14">coverage</text>
             <text x="85" y="15" fill="#010101" fill-opacity=".3">${PERCENT}%</text>
             <text x="85" y="14">${PERCENT}%</text>
           </g>
           </svg>
           SVG

      - name: Fazer Upload
        uses: actions/upload-artifact@v4
        with:
          name: badge-cobertura
          path: coverage-badge.svg
        
      - name: Commit e Push do Badge
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -am "Atualiza a badge de cobertura: ${{ steps.badge.outputs.cobertura || '' }}"
          git push origin main
