name: CI com badge estático

on: [push]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com cobertura
        run: pytest -v --cov=sisrel --cov-report=xml:coverage.xml

      - name: Calcular Cobertura e Cor
        id: coverage_data
        run: |
          # Extrai o valor da cobertura (0.x) do coverage.xml
           COVERAGE=$(grep -oPm1 '(?<=line-rate=")[^"]+' coverage.xml)
           PERCENT=$(python -c "print(int(float('${COVERAGE}')*100))")

           echo "Cobertura: ${PERCENT}%"

           # Define cor conforme o nível (HEX válido)
           if   [ "${PERCENT}" -ge 90 ]; then COLOR="brightgreen";      # brightgreen
           elif [ "${PERCENT}" -ge 75 ]; then COLOR="yellowgreen";   # green
           elif [ "${PERCENT}" -ge 50 ]; then COLOR="orange";   # yellow
           else                             COLOR="red";     # red
           fi

           echo "percent=${PERCENT}" >> "$GITHUB_OUTPUT"
           echo "color=${COLOR}" >> "$GITHUB_OUTPUT"

      - name: Gerar coverage.json
        run: |
          PERCENT='${{ steps.coverage_data.outputs.percent }}'
          COLOR='${{ steps.coverage_data.outputs.color }}'

          echo "Gerando coverage.json com ${PERCENT}% e cor ${COLOR}"

          cat > coverage.json << EOF
          {
            "schemaVersion": 1,
            "label": "coverage",
            "message": "${PERCENT}%",
            "color": "${COLOR}"
          }
          EOF
          echo "Conteudo do coverage.json"
          cat coverage.json

      - name: Commit e Push do Badge
        if: ${{ success() }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git commit -am "Atualiza a badge de cobertura: ${{ steps.badge.outputs.cobertura || '' }}"
          git push origin main
